### ISSUE TITLE
 SimMIM pre-training script: error: the following arguments are required: --local_rank

### ISSUE THREAD

**Issue by mahrokh3409** [mmendiet/GFM#4]
Dear Community,

I tried to run the provided basic command for pretraining **python -m torch.distributed.launch --nproc_per_node 8  main_teacher.py \
--cfg configs/simmim_pretrain__swin_base__img192_window6__100ep.yaml --batch-size 128 \
--data-path ~/GeoPile/GeoPileV0/ --tag gfm --pretrained ~/output/simmim_finetune/swin_base_patch4_window7_224_22k.pth** 
However, I'm getting the below error
  _

> warnings.warn(
> WARNING:torch.distributed.run:
> *****************************************
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
> *****************************************
> usage: SimMIM pre-training script --cfg FILE [--opts OPTS [OPTS ...]] [--batch-size BATCH_SIZE] [--data-path DATA_PATH] [--pretrained PRETRAINED] [--resume RESUME]
>                                   [--accumulation-steps ACCUMULATION_STEPS] [--use-checkpoint] [--amp-opt-level {O0,O1,O2}] [--output PATH] [--tag TAG] [--alpha ALPHA]
>                                   --local_rank LOCAL_RANK
> SimMIM pre-training script: error: the following arguments are required: --local_rank
> usage: SimMIM pre-training script --cfg FILE [--opts OPTS [OPTS ...]] [--batch-size BATCH_SIZE] [--data-path DATA_PATH] [--pretrained PRETRAINED] [--resume RESUME]
>                                   [--accumulation-steps ACCUMULATION_STEPS] [--use-checkpoint] [--amp-opt-level {O0,O1,O2}] [--output PATH] [--tag TAG] [--alpha ALPHA]
>                                   --local_rank LOCAL_RANK
> SimMIM pre-training script: error: the following arguments are required: --local_rank
> usage: SimMIM pre-training script --cfg FILE [--opts OPTS [OPTS ...]] [--batch-size BATCH_SIZE] [--data-path DATA_PATH] [--pretrained PRETRAINED] [--resume RESUME]
>                                   [--accumulation-steps ACCUMULATION_STEPS] [--use-checkpoint] [--amp-opt-level {O0,O1,O2}] [--output PATH] [--tag TAG] [--alpha ALPHA]
>                                   --local_rank LOCAL_RANK
> SimMIM pre-training script: error: the following arguments are required: --local_rank
> usage: SimMIM pre-training script --cfg FILE [--opts OPTS [OPTS ...]] [--batch-size BATCH_SIZE] [--data-path DATA_PATH] [--pretrained PRETRAINED] [--resume RESUME]
>                                   [--accumulation-steps ACCUMULATION_STEPS] [--use-checkpoint] [--amp-opt-level {O0,O1,O2}] [--output PATH] [--tag TAG] [--alpha ALPHA]
>                                   --local_rank LOCAL_RANK
> SimMIM pre-training script: error: the following arguments are required: --local_rank
> usage: SimMIM pre-training script --cfg FILE [--opts OPTS [OPTS ...]] [--batch-size BATCH_SIZE] [--data-path DATA_PATH] [--pretrained PRETRAINED] [--resume RESUME]
>                                   [--accumulation-steps ACCUMULATION_STEPS] [--use-checkpoint] [--amp-opt-level {O0,O1,O2}] [--output PATH] [--tag TAG] [--alpha ALPHA]
>                                   --local_rank LOCAL_RANK
> SimMIM pre-training script: error: the following arguments are required: --local_rank
> usage: SimMIM pre-training script --cfg FILE [--opts OPTS [OPTS ...]] [--batch-size BATCH_SIZE] [--data-path DATA_PATH] [--pretrained PRETRAINED] [--resume RESUME]
>                                   [--accumulation-steps ACCUMULATION_STEPS] [--use-checkpoint] [--amp-opt-level {O0,O1,O2}] [--output PATH] [--tag TAG] [--alpha ALPHA]
>                                   --local_rank LOCAL_RANK
> SimMIM pre-training script: error: the following arguments are required: --local_rank
> usage: SimMIM pre-training script --cfg FILE [--opts OPTS [OPTS ...]] [--batch-size BATCH_SIZE] [--data-path DATA_PATH] [--pretrained PRETRAINED] [--resume RESUME]
>                                   [--accumulation-steps ACCUMULATION_STEPS] [--use-checkpoint] [--amp-opt-level {O0,O1,O2}] [--output PATH] [--tag TAG] [--alpha ALPHA]
>                                   --local_rank LOCAL_RANK
> SimMIM pre-training script: error: the following arguments are required: --local_rank
> usage: SimMIM pre-training script --cfg FILE [--opts OPTS [OPTS ...]] [--batch-size BATCH_SIZE] [--data-path DATA_PATH] [--pretrained PRETRAINED] [--resume RESUME]
>                                   [--accumulation-steps ACCUMULATION_STEPS] [--use-checkpoint] [--amp-opt-level {O0,O1,O2}] [--output PATH] [--tag TAG] [--alpha ALPHA]
>                                   --local_rank LOCAL_RANK
> SimMIM pre-training script: error: the following arguments are required: --local_rank
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 44681) of binary: /home/abd037/anaconda3/envs/SimMIM/bin/python
> Traceback (most recent call last):
>   File "/home/abd037/anaconda3/envs/SimMIM/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/abd037/anaconda3/envs/SimMIM/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/abd037/anaconda3/envs/SimMIM/lib/python3.8/site-packages/torch/distributed/launch.py", line 196, in <module>
>     main()
>   File "/home/abd037/anaconda3/envs/SimMIM/lib/python3.8/site-packages/torch/distributed/launch.py", line 192, in main
>     launch(args)
>   File "/home/abd037/anaconda3/envs/SimMIM/lib/python3.8/site-packages/torch/distributed/launch.py", line 177, in launch
>     run(args)
>   File "/home/abd037/anaconda3/envs/SimMIM/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
>     elastic_launch(
>   File "/home/abd037/anaconda3/envs/SimMIM/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/home/abd037/anaconda3/envs/SimMIM/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ============================================================
> main_teacher.py FAILED
> ------------------------------------------------------------
> Failures:
> [1]:
>   time      : 2023-11-22_15:21:44
>   host      : ??????
>   rank      : 1 (local_rank: 1)
>   exitcode  : 2 (pid: 44682)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> [2]:
>   time      : 2023-11-22_15:21:44
>   host      : ??????
>   rank      : 2 (local_rank: 2)
>   exitcode  : 2 (pid: 44683)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> [3]:
>   time      : 2023-11-22_15:21:44
>   host      : ??????
>   rank      : 3 (local_rank: 3)
>   exitcode  : 2 (pid: 44684)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> [4]:
>   time      : 2023-11-22_15:21:44
>   host      : ??????
>   rank      : 4 (local_rank: 4)
>   exitcode  : 2 (pid: 44685)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> [5]:
>   time      : 2023-11-22_15:21:44
>   host      : ??????
>   rank      : 5 (local_rank: 5)
>   exitcode  : 2 (pid: 44686)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> [6]:
>   time      : 2023-11-22_15:21:44
>   host      : ??????r
>   rank      : 6 (local_rank: 6)
>   exitcode  : 2 (pid: 44687)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> [7]:
>   time      : 2023-11-22_15:21:44
>   host      : ??????
>   rank      : 7 (local_rank: 7)
>   exitcode  : 2 (pid: 44688)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ------------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2023-11-22_15:21:44
>   host      : ??????
>   rank      : 0 (local_rank: 0)
>   exitcode  : 2 (pid: 44681)
>   error_file: <N/A>
>   traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
> ============================================================

_
I do appreciate your help.

Kind Regards,
Mah

**Comment by Hoteryoung** [comment]
You may try to remove this argument for both the main function and torch.nn.parallel.DistributedDataParallel()
I use Slurm to start training on multi-nodes, but I think torch.distributed.launch should work as well.

**Comment by mahrokh3409** [comment]
Hi @Hoteryoung ,
Thank you for getting back to me. I appreciate your assistance. I was able to fix the issue and successfully fine-tune the model, resulting in the creation of the file named 'ckpt_epoch_max.pth.' However, I couldn't find any related file or instructions on how to perform inference on the fine-tuned model. Could you please provide guidance on this matter? Your help is greatly appreciated

Kind Regards,
Mahrokh

**Comment by Hoteryoung** [comment]
Hi @mahrokh3409
I ask the same question in issue 6.
However, this is just for convenience.
Actually, you can do inference by bypassing the finetune training and saving the result in the validate function.

**Comment by funny000** [comment]
Hi @Hoteryoung
When fine-tune or retrain gfm model use the GeoPile dataset, How use memory  of gpu?
I try fine-tune or retrain the model, But don't know how do it?

**Comment by funny000** [comment]
Hi @mahrokh3409 
Can you tell me some information about the problem?
When fine-tune or retrain gfm model use the GeoPile dataset, How use memory of gpu?
